"""Contract-level summary: type classification, parties/dates/obligations
extraction, and risk aggregation. Requires Sprint 6's clause analyses to
already exist for the document (status=analyzed). Risk counts are
computed in code from ClauseAnalysis.risk_level -- never re-asked of the
LLM; only a short narrative is generated by the LLM from that computed
breakdown, so the numbers themselves can never be hallucinated.
"""
import logging

from sqlalchemy.orm import Session

from app.core.clause_taxonomy import ClauseType, RiskLevel
from app.core.contract_taxonomy import VALID_CONTRACT_TYPES, ContractType
from app.core.exceptions import ConflictError, NotFoundError, RateLimitedError
from app.db.analysis_repository import ClauseAnalysisRepository, ContractSummaryRepository
from app.db.chunk_repository import ChunkRepository
from app.models.analysis import ContractSummary
from app.models.document import DocumentStatus
from app.prompts.summary_prompt import (
    EXTRACTION_SYSTEM_PROMPT,
    NARRATIVE_SYSTEM_PROMPT,
    build_extraction_prompt,
    build_narrative_prompt,
)
from app.services import document_service
from app.services.citation_verification import parse_llm_json, verify_citations
from app.services.llm_service import get_llm_provider

logger = logging.getLogger(__name__)

# How many leading (by chunk_index) chunks to treat as the preamble/
# recitals region likely to name the parties and effective date.
MAX_PREAMBLE_CHUNKS = 2


def summarize(db: Session, document_id: int) -> ContractSummary:
    """Runs contract-type classification, parties/dates/obligations
    extraction, and risk aggregation, then persists the result. Safe to
    call again -- the summary is updated in place, not duplicated."""
    document = document_service.get_document(db, document_id)
    if document.status != DocumentStatus.ANALYZED.value:
        raise ConflictError(
            f"Document {document_id} must have clause analysis completed before summarizing "
            f"(current status: '{document.status}'). Run POST /documents/{document_id}/analyze-clauses first."
        )

    clause_rows = ClauseAnalysisRepository(db).list_by_document(document_id)
    if not clause_rows:
        raise ConflictError(f"Document {document_id} has no clause analysis results to summarize from.")

    extraction_chunks = _gather_extraction_chunks(db, document_id, clause_rows)
    extraction = _extract_contract_details(extraction_chunks)

    risk_counts = _compute_risk_counts(clause_rows)
    narrative = _generate_risk_narrative(risk_counts, clause_rows)

    fields = {
        "contract_type": extraction["contract_type"],
        "parties": extraction["parties"],
        "effective_date": extraction["effective_date"],
        "expiration_date": extraction["expiration_date"],
        "key_obligations": extraction["key_obligations"],
        "risk_summary_narrative": narrative,
        "risk_counts": risk_counts,
    }

    repo = ContractSummaryRepository(db)
    summary = repo.upsert(document_id, fields)
    db.commit()
    db.refresh(summary)
    return summary


def get_summary(db: Session, document_id: int) -> ContractSummary:
    document_service.get_document(db, document_id)  # raises NotFoundError if missing
    summary = ContractSummaryRepository(db).get_for_document(document_id)
    if summary is None:
        raise NotFoundError(
            f"No summary found for document {document_id}. Run POST /documents/{document_id}/summarize first."
        )
    return summary


def get_full_report(db: Session, document_id: int) -> dict:
    document = document_service.get_document(db, document_id)
    clauses = ClauseAnalysisRepository(db).list_by_document(document_id)
    summary = ContractSummaryRepository(db).get_for_document(document_id)
    return {"document": document, "summary": summary, "clauses": clauses}


def _gather_extraction_chunks(db: Session, document_id: int, clause_rows) -> list[dict]:
    """Curated chunk set for classification/extraction: the leading
    (preamble/recitals) chunks plus any chunks already cited by the
    PARTIES/EFFECTIVE_DATE clause analyses -- never the whole document."""
    all_chunks = ChunkRepository(db).list_by_document(document_id)
    chunk_by_id = {chunk.id: chunk for chunk in all_chunks}

    preamble_chunks = sorted(all_chunks, key=lambda chunk: chunk.chunk_index)[:MAX_PREAMBLE_CHUNKS]

    tagged_chunk_ids: list[int] = []
    for row in clause_rows:
        if row.clause_type in (ClauseType.PARTIES.value, ClauseType.EFFECTIVE_DATE.value) and row.present and row.citations:
            for citation in row.citations:
                chunk_id = citation.get("chunk_id")
                if chunk_id is not None:
                    tagged_chunk_ids.append(chunk_id)

    merged = []
    seen_ids: set[int] = set()
    for chunk in list(preamble_chunks) + [chunk_by_id[cid] for cid in tagged_chunk_ids if cid in chunk_by_id]:
        if chunk.id not in seen_ids:
            seen_ids.add(chunk.id)
            merged.append(chunk)

    return [{"chunk_id": chunk.id, "section_label": chunk.section_label, "text": chunk.text} for chunk in merged]


def _default_extraction() -> dict:
    return {
        "contract_type": ContractType.GENERAL_BUSINESS.value,
        "parties": [],
        "effective_date": None,
        "expiration_date": None,
        "key_obligations": [],
    }


def _extract_contract_details(chunks: list[dict]) -> dict:
    if not chunks:
        return _default_extraction()

    prompt = build_extraction_prompt(chunks)
    provider = get_llm_provider()
    raw_response = provider.generate(prompt, system=EXTRACTION_SYSTEM_PROMPT)

    return _parse_extraction_response(raw_response, chunks)


def _parse_extraction_response(raw_response: str, chunks: list[dict]) -> dict:
    chunk_text_by_id = {chunk["chunk_id"]: chunk["text"] for chunk in chunks}

    data = parse_llm_json(raw_response, required_keys={"contract_type": str, "parties": list, "citations": list})
    if data is None:
        logger.warning("Could not parse contract summary extraction response; using safe defaults.")
        return _default_extraction()

    verified_citations = verify_citations(data["citations"], chunk_text_by_id)
    if not verified_citations:
        # Consistent with the rest of the app: an extraction with zero
        # grounded citations is not trusted, even if it "looks" plausible.
        logger.info("Contract summary extraction had zero verified citations; using safe defaults.")
        return _default_extraction()

    contract_type = data.get("contract_type")
    if contract_type not in VALID_CONTRACT_TYPES:
        contract_type = ContractType.GENERAL_BUSINESS.value

    parties = _clean_parties(data.get("parties"))
    key_obligations = _clean_obligations(data.get("key_obligations"))

    effective_date = data.get("effective_date")
    if not isinstance(effective_date, str):
        effective_date = None

    expiration_date = data.get("expiration_date")
    if not isinstance(expiration_date, str):
        expiration_date = None

    return {
        "contract_type": contract_type,
        "parties": parties,
        "effective_date": effective_date,
        "expiration_date": expiration_date,
        "key_obligations": key_obligations,
    }


def _clean_parties(parties) -> list[dict]:
    if not isinstance(parties, list):
        return []
    cleaned = []
    for party in parties:
        if isinstance(party, dict) and isinstance(party.get("name"), str):
            role = party.get("role")
            cleaned.append({"name": party["name"], "role": role if isinstance(role, str) else None})
    return cleaned


def _clean_obligations(obligations) -> list[dict]:
    if not isinstance(obligations, list):
        return []
    cleaned = []
    for obligation in obligations:
        if (
            isinstance(obligation, dict)
            and isinstance(obligation.get("party"), str)
            and isinstance(obligation.get("obligation"), str)
        ):
            cleaned.append({"party": obligation["party"], "obligation": obligation["obligation"]})
    return cleaned


def _compute_risk_counts(clause_rows) -> dict:
    """Computed in code from persisted ClauseAnalysis rows -- counts risk
    levels only among clauses found present (an absent clause's risk_level
    is always "unknown" and would just be noise here)."""
    counts = {level.value: 0 for level in RiskLevel}
    for row in clause_rows:
        if row.present:
            key = row.risk_level if row.risk_level in counts else RiskLevel.UNKNOWN.value
            counts[key] += 1
    return counts


def _generate_risk_narrative(risk_counts: dict, clause_rows) -> str:
    high_risk_clauses = [
        {"clause_type": row.clause_type, "risk_explanation": row.risk_explanation}
        for row in clause_rows
        if row.present and row.risk_level == RiskLevel.HIGH.value and row.risk_explanation
    ]

    prompt = build_narrative_prompt(risk_counts, high_risk_clauses)

    try:
        provider = get_llm_provider()
        raw_response = provider.generate(prompt, system=NARRATIVE_SYSTEM_PROMPT)
    except (RateLimitedError, NotImplementedError) as exc:
        # The narrative is a cheap embellishment on top of already-solid,
        # code-computed risk_counts -- not worth failing the whole summary
        # over, unlike the primary extraction call above.
        logger.warning("Risk narrative generation unavailable (%s); using a templated fallback.", exc)
        return _fallback_narrative(risk_counts)

    data = parse_llm_json(raw_response, required_keys={"narrative": str})
    if data is None or not data["narrative"].strip():
        return _fallback_narrative(risk_counts)
    return data["narrative"]


def _fallback_narrative(risk_counts: dict) -> str:
    return (
        f"{risk_counts.get('high', 0)} high-risk, {risk_counts.get('medium', 0)} medium-risk, and "
        f"{risk_counts.get('low', 0)} low-risk clause(s) were identified based on automated clause "
        "analysis. This is a heuristic review signal, not legal advice."
    )
